In [1]:
import numpy as np

In [4]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [5]:
#input dataset
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [17]:
#output dataset
Y = np.array([[0,0,0,1]]).T
print(Y)

[[0]
 [0]
 [0]
 [1]]


In [7]:
#seed random numbers to make calulation
#deterministic (just a good practice)

np.random.seed(1)

In [12]:
#initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
print(syn0)

[[-0.62747958]
 [-0.30887855]
 [-0.20646505]]


In [23]:
for iter in range(10000):
    
    #forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    #how much did we miss
    l1_error = Y - l1
    
    #mutiply how much we missed by the
    #slope of the sigmod at the values in l1
    l1_delta = l1_error*nonlin(l1, True)
    
    #update weights
    syn0 += np.dot(l0.T, l1_delta)
    

In [27]:
print("output of the training :")
print(l1)   

output of the training :
[[5.48146665e-06]
 [1.63717872e-02]
 [1.63717872e-02]
 [9.80597412e-01]]
