In [2]:
import numpy as np

In [3]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [4]:
#input dataset
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [5]:
#output dataset
Y = np.array([[0,0,0,1]]).T
print(Y)

[[0]
 [0]
 [0]
 [1]]


In [6]:
#seed random numbers to make calulation
#deterministic (just a good practice)

np.random.seed(1)

In [7]:
#initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

print(syn0)

print(syn1)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [8]:
for iter in range(60000):
    
    #forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    #how much did we miss
    l2_error = Y - l2
    
    if(iter%10000 == 0):
        print(l1)
        print("error : {0}".format(str(np.mean(np.abs(l2_error)))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2, deriv = True)
    
    #how much did each l1 value contribute to the l2 error (according to the weight)
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1 ?
    # were we really sure ? if so, dont change too much
    l1_delta = l1_error * nonlin(l1, deriv = True)
    

    #update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta) 
    

[[0.44856632 0.51939863 0.45968497 0.59156505]
 [0.28639589 0.32350963 0.31236398 0.51538526]
 [0.40795614 0.62674606 0.23841622 0.49377636]
 [0.25371248 0.42628115 0.14321233 0.41732254]]
error : 0.49045475363302393
[[0.93652327 0.19094822 0.98881655 0.7541582 ]
 [0.30399394 0.31397825 0.69683053 0.35296006]
 [0.77963446 0.86099106 0.79539452 0.44045602]
 [0.09480621 0.92314182 0.09178196 0.12278916]]
error : 0.005754408734440181
[[0.94452689 0.16716842 0.99074674 0.76965609]
 [0.30865308 0.29730062 0.70426423 0.35257252]
 [0.7918487  0.85487335 0.80938494 0.45749427]
 [0.09070109 0.92546246 0.08629177 0.1208341 ]]
error : 0.00392247080073151
[[0.94858628 0.15442396 0.99166677 0.77819026]
 [0.31159901 0.28854899 0.70851174 0.35208021]
 [0.79816249 0.85033745 0.81649541 0.46736318]
 [0.08843679 0.92656781 0.08331098 0.11964544]]
error : 0.0031432670883449853
[[0.95123085 0.14584961 0.9922447  0.78401332]
 [0.31381419 0.28273101 0.71150303 0.35161111]
 [0.80230616 0.84664428 0.82111672 

In [12]:
print("output of the training :")
print(l1)   

output of the training :
[[0.95466356 0.13438137 0.99296948 0.7918958 ]
 [0.31714211 0.27503328 0.71570769 0.35078419]
 [0.80770203 0.84071372 0.8270812  0.48382779]
 [0.08478522 0.92804752 0.07855898 0.11746103]]
