In [2]:
import numpy as np

In [3]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [4]:
#input dataset
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [5]:
#output dataset
Y = np.array([[0,0,0,1]]).T
print(Y)

[[0]
 [0]
 [0]
 [1]]


In [6]:
#seed random numbers to make calulation
#deterministic (just a good practice)

np.random.seed(1)

In [8]:
#initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

print(syn0)

print(syn1)

[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]]
[[-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


In [23]:
for iter in range(60000):
    
    #forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    #how much did we miss
    l2_error = y - l2
    
    if(i%10000 == 0):
        print("error : {0}".format(str(np.mean(np.abs(l2_error)))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2, deriv = True)
    
    #how much did each l1 value contribute to the l2 error (according to the weight)
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1 ?
    # were we really sure ? if so, dont change too much
    l1_delta = l1_error * nonlin(l1, deriv = True)
    

    #update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta) 
    

In [27]:
print("output of the training :")
print(l1)   

output of the training :
[[5.48146665e-06]
 [1.63717872e-02]
 [1.63717872e-02]
 [9.80597412e-01]]
